import type { BillingUnit } from '@/types/models'

import type { InvoicePdfLocale } from './types'

export type InvoicePdfStrings = {
  invoiceTitle: string
  dateLabel: string
  invoiceNoLabel: string
  dueDateLabel: string
  billTo: string
  tableDesc: string
  tableQty: string
  tableUnit: string
  tableUnitPrice: string
  tableAmount: string
  subtotal: string
  vatRate: string
  vatReverseCharge: string
  vatExempt: string
  total: string
  ibanLabel: string
  bicLabel: string
  paymentTermsTitle: string
  latePenaltyTitle: string
  sepaQrCaption: string
  thanks: string
  generatedBy: string
  defaultPaymentTerms: string
  defaultLatePenalty: string
  autoliquidationVat: string
  billingUnit: (u: BillingUnit) => string
}

const fr: InvoicePdfStrings = {
  invoiceTitle: 'FACTURE',
  dateLabel: 'DATE',
  invoiceNoLabel: 'N° FACTURE',
  dueDateLabel: 'ÉCHÉANCE',
  billTo: 'FACTURER À',
  tableDesc: 'DESCRIPTION',
  tableQty: 'QTÉ',
  tableUnit: 'UNITÉ',
  tableUnitPrice: 'PU HT',
  tableAmount: 'MONTANT HT',
  subtotal: 'SOUS-TOTAL HT',
  vatRate: 'TAUX TVA',
  vatReverseCharge: 'Autoliquidation TVA',
  vatExempt: 'Exonération / TVA non applicable',
  total: 'TOTAL TTC',
  ibanLabel: 'IBAN',
  bicLabel: 'BIC',
  paymentTermsTitle: 'Conditions de paiement',
  latePenaltyTitle: 'Pénalités de retard',
  sepaQrCaption: 'Paiement SEPA (QR)',
  thanks: 'MERCI DE VOTRE CONFIANCE.',
  generatedBy: 'Document généré par CRA Studio',
  defaultPaymentTerms:
    'Paiement à 30 jours net à réception de facture, sauf mention contraire sur le bon de commande.',
  defaultLatePenalty:
    'En cas de retard, des pénalités au taux légal en vigueur ainsi qu’une indemnité forfaitaire pour frais de recouvrement de 40 € (art. L441-6 C. com.) sont dues de plein droit.',
  autoliquidationVat:
    'TVA due par le preneur — autoliquidation (réf. art. 283-2 du CGI lorsque les conditions sont réunies).',
  billingUnit: (u) => {
    switch (u) {
      case 'day':
        return 'jour(s)'
      case 'month':
        return 'mois'
      case 'hour':
        return 'h'
      case 'flat':
        return 'forfait'
      default:
        return ''
    }
  },
}

const en: InvoicePdfStrings = {
  invoiceTitle: 'INVOICE',
  dateLabel: 'DATE',
  invoiceNoLabel: 'INVOICE NO.',
  dueDateLabel: 'DUE DATE',
  billTo: 'BILL TO',
  tableDesc: 'DESCRIPTION',
  tableQty: 'QTY',
  tableUnit: 'UNIT',
  tableUnitPrice: 'UNIT PRICE (EXCL. VAT)',
  tableAmount: 'AMOUNT (EXCL. VAT)',
  subtotal: 'SUBTOTAL (EXCL. VAT)',
  vatRate: 'VAT RATE',
  vatReverseCharge: 'Reverse charge VAT',
  vatExempt: 'Exempt / VAT not applicable',
  total: 'TOTAL (INCL. VAT)',
  ibanLabel: 'IBAN',
  bicLabel: 'BIC',
  paymentTermsTitle: 'Payment terms',
  latePenaltyTitle: 'Late payment penalties',
  sepaQrCaption: 'SEPA payment (QR)',
  thanks: 'THANK YOU FOR YOUR BUSINESS.',
  generatedBy: 'Document generated by CRA Studio',
  defaultPaymentTerms: 'Payment due within 30 days of invoice date unless otherwise agreed in writing.',
  defaultLatePenalty:
    'In case of late payment, statutory interest and a fixed recovery fee of €40 may apply in accordance with applicable law.',
  autoliquidationVat:
    'VAT to be paid by the customer — reverse charge (where the legal conditions of art. 283-2 CGI are met).',
  billingUnit: (u) => {
    switch (u) {
      case 'day':
        return 'day(s)'
      case 'month':
        return 'month(s)'
      case 'hour':
        return 'h'
      case 'flat':
        return 'flat fee'
      default:
        return ''
    }
  },
}

export function getInvoicePdfStrings(locale: InvoicePdfLocale): InvoicePdfStrings {
  return locale === 'en' ? en : fr
}
